[project]
name = "rtmp-transcription-platform"
version = "0.1.0"
description = "RTMP live streaming platform with real-time transcription"
authors = []
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []
