name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            GLADIA_API_KEY=${{ secrets.GLADIA_API_KEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 5.161.110.155
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop rtmp-server || true
            docker rm rtmp-server || true
            docker run -d \
              --name rtmp-server \
              -p 1935:1935 \
              -p 8000:8000 \
              -e GLADIA_API_KEY=${{ secrets.GLADIA_API_KEY }} \
              -e WEBHOOK_URL=http://localhost:8000/webhook \
              ghcr.io/${{ github.repository }}:latest